SN/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'SN'
urlpatterns = [

    # SN/
    re_path(r'^$', views.home, name='default'),

    # SN/profile/  --> current logged in user's profile
    re_path(r'^profile/$', views.MyProfileView, name='myprofile'),

    # SN/profile/4  --> viewing another user's profile
    re_path(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileView, name='profile'),

    # SN/profile/4/report_user/
    re_path(r'^profile/(?P<pk>[0-9]+)/report_user/$', views.ReportUserView.as_view(), name='report_user'),

    # SN/profile/4/report_user/
    re_path(r'^posts/(?P<pk>[0-9]+)/report_post/$', views.ReportPostView.as_view(), name='report_post'),

    # SN/friends/ --> Social page
    re_path(r'^friends/$', views.FriendsView, name='friends'),

    # SN/register/
    re_path(r'^register/$', views.UserFormView.as_view(), name='register'),

    # SN/login/
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name='SN/login.html'), name='login'),

    # SN/logout/
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    # SN/addpost
    re_path(r'^addpost/$', views.Addpostview.as_view(), name='addpost'),

    url(r'^connect/(?P<operation>.+)/(?P<pk>[0-9]+)/$', views.change_friends, name='change_friends'),

    # SN/home
    re_path(r'^home/$', views.home, name='home'),

    url(r'^posts/(?P<pk>[0-9]+)/$', views.post_details, name='post_details'),

    # SN/posts/1/delete_post
    url(r'^posts/(?P<pk>[0-9]+)/delete_post$', views.PostDelete.as_view(), name='delete_post'),

    url(r'^posts/(?P<pk>[0-9]+)/edit_post/$', views.PostUpdate.as_view(), name='edit_post'),

    # SN/posts/2/3/delete_comment
    url(r'^posts/(?P<pk>[0-9]+)/delete_comment/$', views.CommentDelete.as_view(), name='delete_comment'),

    # SN/profile/1/edit_profile
    re_path(r'^profile/(?P<pk>[0-9]+)/edit_profile/$', views.UserUpdate.as_view(), name='edit_profile'),

    # SN/profile/5/delete_profile
    re_path(r'^profile/(?P<pk>[0-9]+)/delete_profile/$', views.UserDelete.as_view(), name='delete_profile'),

    # SN/posts/7/addcomment
    url(r'^posts/(?P<pk>[0-9]+)/addcomment/$', views.add_comment_to_post, name='addcomment'),

    # SN/posts/1/Like(Unlike)
    url(r'^posts/(?P<pk>[0-9]+)/(?P<operation>.+)/$', views.change_like_post, name='change_like'),

    # SN/graph/
    url(r'^graph/$', views.graph, name='graph'),

    # SN/search_results/
    re_path(r'^search_results/$', views.search, name='search_results'),

    # SN/analysis/
    re_path(r'^analysis/$', views.analysis, name='analysis'),
    
    
    # SN/creategroup
    re_path(r'^creategroup/$', views.CreateGroupView.as_view(), name='create_group'),

    # SN/groups/
    re_path(r'^groups/$', views.groupslist, name='groups'),
    # SN/change_member
    url(r'^group_change_members/(?P<operation>.+)/(?P<pk>[0-9]+)/$', views.change_group_member, name='change_members'),

    # SN/group/pk
    re_path(r'^group/(?P<pk>[0-9]+)/$', views.group_details, name='group_details'),
    # SN/group/pk/members
    re_path(r'^group/(?P<pk>[0-9]+)/members$', views.group_members, name='group_members'),
    # SN/group/pk/addpost
    re_path(r'^group/(?P<pk>[0-9]+)/addpost$', views.Addpostgroup.as_view(), name='addpost_group'),

    # SN/group/pk/delete
    re_path(r'^group/(?P<pk>[0-9]+)/delete$', views.delete_group, name='delete_group'),
# SN/group/pk/delete_member
    re_path(r'^group/(?P<group_pk>[0-9]+)/delete_member/(?P<member_pk>[0-9]+)$', views.delete_member, name='delete_member'),


]

socialNetworkFinal/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from SN import views

urlpatterns = [
    path('admin/', admin.site.urls, ),
    path('SN/', include('SN.urls')),
    path('usersjason/', views.UsersList.as_view()),
    re_path(r'^usersjason/(?P<pk>[0-9]+)/', views.SNUserDetail.as_view()),
    path('postsjason/', views.PostsList.as_view()),
    path('excelreport/', views.ToExcel),
]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html', 'xml'])

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SN/forms.py
from .models import SNUser, Post, Comment, ReportUser, ReportPost, Group
from django import forms


class SNUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = SNUser
        fields = ['first_name', 'last_name', 'username', 'email', 'password', 'location', 'profile_pic', 'birth_date',
                  'gender', 'bio']


class AddPostForm(forms.ModelForm):
    text = forms.CharField(
        max_length=1000,
        widget=forms.Textarea(attrs={'rows': 5, 'class': "form-control"}),
    )

    class Meta:
        model = Post
        fields = ['text', 'photo']


class AddCommentForm(forms.ModelForm):
    text = forms.CharField(
        max_length=1000,
        widget=forms.Textarea(attrs={'rows': 5, 'class': "form-control"}),
    )

    class Meta:
        model = Comment
        fields = ['text']


class ReportUserForm(forms.ModelForm):
    CHOICES = [('select1', 'This is a fake account'),
               ('select2', 'This person has inappropriate personal information (profile picture, bio section...etc.)'),
               ('select3', 'This person is sharing inappropriate/offensive posts'),
               ('select4', 'This person is annoying me'),
               ('select5', 'Other...')
               ]

    text = forms.CharField(required=False,
                           max_length=1000,
                           widget=forms.Textarea(attrs={'rows': 5, 'class': "form-control"}),
                           )

    report_option = forms.ChoiceField(choices=CHOICES, required=True, widget=forms.RadioSelect())

    class Meta:
        model = ReportUser
        fields = ['report_option', 'text']


class ReportPostForm(forms.ModelForm):
    CHOICES = [('select1', 'This post is annoying/not interesting'),
               ('select2', "The post's content is offensive/abusive (bad language,threatening,violence,..etc."),
               ('select3', "Spam post"),
               ('select4', 'Other...'),
               ]

    text = forms.CharField(required=False,
                           max_length=1000,
                           widget=forms.Textarea(attrs={'rows': 5, 'class': "form-control"}),
                           )

    report_option = forms.ChoiceField(choices=CHOICES, required=True, widget=forms.RadioSelect())

    class Meta:
        model = ReportPost
        fields = ['report_option', 'text']
        
class CreateGroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ['name', 'photo']


SN/views.py
from django.views import generic
from .models import SNUser, Post, Friend, Like, Comment, ReportUser, ReportPost, Group
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import SNUserForm, AddPostForm, AddCommentForm, ReportUserForm, ReportPostForm, CreateGroupForm
from django.shortcuts import render, redirect, get_object_or_404, Http404
from django.db.models import Count, Max
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import SNUserSerializer, PostSerializer
from rest_framework import status
from django.contrib import messages
import os

def ProfileView(request, pk=None):
    if request.user.is_anonymous is True:
        return redirect('SN:login')
    if pk:
        friendsobject, created = Friend.objects.get_or_create(current_user=request.user)
        snuser = SNUser.objects.get(pk=pk)
        if created == False:
            current_user_friend = friendsobject.friends.all()
            if snuser in current_user_friend:
                addremove = "Remove"
            else:
                addremove = "Add"
        else:
            addremove = "Add"
        return render(request, 'SN/profile.html', {'snuser': snuser, 'addremove': addremove, 'current_user':request.user})
    else:
        return


def MyProfileView(request):
    if request.user.is_anonymous is True:
        return redirect('SN:login')

    snuser = request.user

    return render(request, 'SN/profile.html', {'snuser': snuser,'current_user':request.user})


# user
class UserFormView(View):
    template_name = 'SN/registration_form.html'
    form_class = SNUserForm

    # display blank form for signup

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):

        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():

            user = form.save(commit=False)

            # clean data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return user object if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('SN:home')

        return render(request, self.template_name, {'form': form})


class UserUpdate(UpdateView):
    model = SNUser
    fields = ['first_name', 'last_name', 'username', 'profile_pic', 'birth_date', 'gender']
    success_url = reverse_lazy('SN:myprofile')


class UserDelete(DeleteView):
    model = SNUser
    success_url = reverse_lazy('SN:login')


# user


def home(request):

    if request.user.is_anonymous is True:
        return redirect('SN:login')
    if request.user.is_superuser is True:
        allposts = Post.objects.all()
        template = 'SN/home.html'
        form = AddCommentForm(request.POST)
        context = {'logged_in_user_posts': allposts, 'currentuser' :request.user, 'form' :form}
        return render(request, template, context)

    logged_in_user = request.user
    current_user_posts = Post.objects.filter(owner=logged_in_user, is_group_post=False)  # this user's posts only
    friends_posts = []
    friend_obj = Friend.objects.filter(current_user=logged_in_user)  # all friends of logged-in user
    queryset = SNUser.objects.none()

    for current_friends in friend_obj.all():
        for current_friend in current_friends.friends.all():
            for post in Post.objects.filter(owner=current_friend.pk, is_group_post=False):
                friends_posts.append(post)

    for this_post in current_user_posts:
        if Like.objects.filter(owner=request.user, post=this_post):
            this_post.current_user_like = True
        else:
            this_post.current_user_like = False

    for this_post in friends_posts:
        if Like.objects.filter(owner=request.user, post=this_post):
            this_post.current_user_like = True
        else:
            this_post.current_user_like = False

    # suggested friends part
    friend, create = Friend.objects.get_or_create(current_user=request.user)
    if create == False:
        friendss = friend.friends.all()
        queryset = SNUser.objects.none()

        for frienduser in friendss:
            friendobject, create = Friend.objects.get_or_create(current_user=frienduser)
            if create == False:
                queryset = queryset | friendobject.friends.all()

        friendsoffriends = queryset.exclude(id__in=friendss).exclude(id=request.user.id)
    else:
        friendsoffriends=[]
    # suggested friends part
    template = 'SN/home.html'
    form = AddCommentForm(request.POST)
    context = {'logged_in_user_posts': current_user_posts, 'friends_posts': friends_posts, 'form': form
               , 'friendsoffriends': friendsoffriends, 'currentuser': request.user}
    return render(request, template, context)


# post
class Addpostview(View):

    template_name = 'SN/post_form.html'
    form_class = AddPostForm

    # display blank form for signup

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            # post.photo = request.FILES['photo']
            post.save()
            return redirect('SN:home')
    # return render(request, self.template_name, {'form': form})


def add_comment_to_post(request, pk):
    if request.user.is_anonymous is True:
        return redirect('SN:login')
    this_post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = AddCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = this_post
            comment.owner = request.user
            comment.save()
            return redirect('SN:post_details', pk=pk)
    return redirect('SN:post_details', pk=pk)


def change_like_post(request, operation, pk):
    if request.user.is_anonymous is True:
        return redirect('SN:login')
    this_post = get_object_or_404(Post, pk=pk)
    if operation == 'Like':
        Like.objects.create(post=this_post, owner=request.user)

    elif operation == 'Unlike':
        Like.objects.filter(owner=request.user, post=this_post).delete()

    return redirect('SN:home')


# post


# friend
def FriendsView(request):
    if request.user.is_anonymous is True:
        return redirect('SN:login')
    friend, create = Friend.objects.get_or_create(current_user=request.user)
    if create == False:
        friendss = friend.friends.all()
        queryset = SNUser.objects.none()

        for frienduser in friendss:
            friendobject, create = Friend.objects.get_or_create(current_user=frienduser)
            if create == False:
               queryset = queryset | friendobject.friends.all()

        friendsoffriends = queryset.exclude(id__in=friendss).exclude(id=request.user.id)
    else:
        friendss = None
    followers = []
    allfriendobjects=Friend.objects.all()
    for friendobj in allfriendobjects:
        if request.user in friendobj.friends.all():
            followers.append(friendobj.current_user)

    return render(request, 'SN/friends.html', {'friendss': friendss, 'friendsoffriends': friendsoffriends,'followers': followers})


def change_friends(request, operation, pk):
    if request.user.is_anonymous is True:
        return redirect('SN:login')
    friend = SNUser.objects.get(pk=pk)
    if operation == 'Add':
        Friend.make_friend(request.user, friend)
    elif operation == 'Remove':
        Friend.lose_friend(request.user, friend)
    return redirect('SN:friends')


# friend

def post_details(request, pk):
    if request.user.is_anonymous is True:
        return redirect('SN:login')
    this_post = get_object_or_404(Post, pk=pk)
    template = 'SN/post_details.html'
    fileName, fileExtension = os.path.splitext(this_post.photo.name)
    form = AddCommentForm(request.POST)
    context = {'this_post': this_post, 'form': form, 'fileextension': fileExtension, 'currentuser':request.user}
    return render(request, template, context)


def graph(request):
    if request.user.is_anonymous is True:
        return redirect('SN:login')
    if request.user.is_superuser is False:
        return redirect('/admin/')

    all_users = SNUser.objects.all()
    all_relationships = Friend.objects.all()
    context = {'all_users': all_users, 'all_friends': all_relationships}
    template = 'SN/graph.html'
    return render(request, template, context)


# Search
def search(request):
    if request.user.is_anonymous is True:
        return redirect('SN:login')
    template = 'SN/search_results.html'
    q = request.GET['q']
    search_result = SNUser.objects.filter(first_name__icontains=q) | SNUser.objects.filter(last_name__icontains=q)
    return render(request, template, {'search_result': search_result, 'q': q})


def analysis(request):
    if request.user.is_anonymous is True:
        return redirect('SN:login')
    postswithlikes = Post.objects.annotate(like_count=Count('like'))
    maxnlikes = postswithlikes.aggregate(maxlikes=Max('like_count'))
    nmaxlikes=maxnlikes['maxlikes']
    postwithmaxlikes = postswithlikes.filter(like_count=nmaxlikes).first()

    postswithcomments = Post.objects.annotate(comments_count=Count('comments'))
    maxncomments = postswithcomments.aggregate(maxcomments=Max('comments_count'))

SN/templates/SN/analysis.html
{% extends 'SN/base.html' %}

{% block title %}Analysis{% endblock %}

{% block body %}
    <h1 style="color:silver">Top Posts:</h1>
        <ul>
            <li style="color: silver" type="square">
                <h1 style="color:silver"></h1>
                <h3 style="color:silver"> Most Liked : <a href="{% url 'SN:profile' mlpost.owner.pk %}">{{mlpost.owner}}</a>'s <a href="{% url 'SN:post_details' mlpost.pk %}">Post</a>  with {{ maxlikes }} Likes.</h3>
            </li>
            <li style="color: silver" type="square">
                <h1 style="color:silver"></h1>
                <h3 style="color:silver"> Most Commented on : <a href="{% url 'SN:profile' mcpost.owner.pk %}">{{mcpost.owner}}</a>'s <a href="{% url 'SN:post_details' mcpost.pk %}">Post</a>  with {{ maxcomments }} Comments.</h3>
            </li>
        </ul>
     <h1 style="color:silver">Top Users:</h1>

<ul>
    <li style="color: silver" type="square">
            <h2 style="color:silver">Most Interactive Users:</h2>
            <ul>

                <li style="color: silver" type="circle">
                    <h1 style="color:silver"></h1>
                    <h3 style="color:silver"> {{ maxuserlikes }} likes made by  <a href="{% url 'SN:profile' maxlikesuser.id %}">{{maxlikesuser}}</a>.   </h3>
                </li>
                <li style="color: silver" type="circle">
                    <h1 style="color:silver"></h1>
                    <h3 style="color:silver"> {{ maxusercomments }} comments made by  <a href="{% url 'SN:profile' maxcommentsuser.id %}">{{maxcommentsuser}}</a>.   </h3>
                </li>
            </ul>
    </li>
    <li style="color: silver" type="square">
        <h2 style="color:silver">User following most users:</h2>
        <ul>
            <li style="color: silver" type="circle">
               <h3 style="color:silver">    <a href="{% url 'SN:profile' userwithmaxfriends.id %}">{{userwithmaxfriends}}</a> is following {{ maxfriends }} users.   </h3>
            </li>
        </ul>
    </li>
    <li style="color: silver" type="square">
        <h2 style="color:silver">User with most followers:</h2>
        <ul>
            <li style="color: silver" type="circle">
               <h3 style="color:silver">    <a href="{% url 'SN:profile' maxfollowersuser.id %}">{{maxfollowersuser}}</a> with {{ maxfollowerscount }} followers.   </h3>
            </li>
        </ul>
    </li>
    <li style="color: silver" type="square">
        <h2 style="color:silver">User with most posts:</h2>
        <ul>
            <li style="color: silver" type="circle">
               <h3 style="color:silver">    <a href="{% url 'SN:profile' maxpostsuser.id %}">{{maxpostsuser}}</a> with {{ maxuserposts }} posts.   </h3>
            </li>
        </ul>
    </li>
</ul>

{% endblock %}

SN/templates/SN/friends.html
{% extends 'SN/base.html' %}
{% block title %}Social{% endblock%}
{% block body %}
    <style>
    a{
        color:lightgray
    }
        img{
            margin-left: 20px;
        }
    .panel-transparent {
        background: none;
    }

    .panel-transparent .panel-body{
        background: rgba(46, 51, 56, 0.2);
    }
    </style>
    <br>
{% if friendss %}
    <div class="col-sm-5 ">

    <div class="panel  panel-transparent">
        <div class="panel-body" >
        <h2 style="color: white">Following:</h2>
        <br>
    {% for friend in friendss %}

        <div class="row">&emsp;
            <a href="{% url 'SN:profile' friend.id%}" >&emsp;
                    <div class="col-sm-3">
                    {% if friend.profile_pic %}
                        <img src="{{ friend.profile_pic.url }}" class="img-responsive" style="width:50px;height:50px;">
                    {% else %}
                        <h3>No image to display</h3>
                    {% endif %}
                    </div>
                    <div class="col-sm-6">

                        <h4>{{ friend.first_name }} {{ ' ' }} {{ friend.last_name }}</h4>
                    </div>
                    <div class="col-sm-1">

                        <a href="{% url 'SN:change_friends' "Remove" friend.id %}" class="btn btn-info" role="button">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            Unfollow
                        </a>
                    </div>
            </a>

        </div>
        <br>
    {% endfor %}
        </div></div>
    {% if followers %}



<div class="panel  panel-transparent">
        <div class="panel-body" >

    <h2 style="color: white">Followers:</h2>
<br>
        {% for follower in followers %}
            <div class="row">&emsp;
            <a href="{% url 'SN:profile' follower.id%}" >&emsp;
                    <div class="col-sm-3">
                    {% if follower.profile_pic %}
                        <img src="{{ follower.profile_pic.url }}" class="img-responsive" style="width:50px;height:50px;">
                    {% else %}
                        <h3>No image to display</h3>
                    {% endif %}
                    </div>
                    <div class="col-sm-6">

                        <h4>{{ follower.first_name }} {{ ' ' }} {{ follower.last_name }}</h4>
                    </div>
                    <div class="col-sm-1">


                        {% if follower in friendss%}
                                <a href="{% url 'SN:change_friends' "Remove" follower.id %}" class="btn btn-info" role="button">

                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                    Unfollow
                                </a>
                        {% else %}
                            <a href="{% url 'SN:change_friends' "Add" follower.id %}" class="btn btn-info" role="button">
                             <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            Follow
                        </a>
                        {% endif %}
                    </div>
            </a>

        </div>

                     <br>
        {% endfor %}
        </div></div>
{% endif %}
    </div>
    {% endif %}

    <div class="col-sm-1 "></div>

{%  if friendsoffriends %}
        <div class="col-sm-5 ">

<div class="panel  panel-transparent">
        <div class="panel-body" >

    <h2 style="color: white">People you may know:</h2>
<br>
        {% for user in friendsoffriends %}
            <div class="row">&emsp;
            <a href="{% url 'SN:profile' user.id%}" >&emsp;
                    <div class="col-sm-3">
                    {% if user.profile_pic %}
                        <img src="{{ user.profile_pic.url }}" class="img-responsive" style="width:50px;height:50px;">
                    {% else %}
                        <h3>No image to display</h3>
                    {% endif %}
                    </div>
                    <div class="col-sm-6">

                        <h4>{{ user.first_name }} {{ ' ' }} {{ user.last_name }}</h4>
                    </div>
                    <div class="col-sm-1">

                        <a href="{% url 'SN:change_friends' "Add" user.id %}" class="btn btn-info" role="button">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            Follow
                        </a>
                    </div>
            </a>

        </div>

                     <br>
        {% endfor %}
        </div></div></div>
    {% endif %}





{% endblock %}

SN/templates/SN/group_members.html
{% extends 'SN/base.html' %}

{% block body %}
    <style>
    .btn-group button {
    background-color: #222;
    border-color: #080808;
    border: 1px solid black;
    color: #9d9d9d;
    padding: 10px 24px; /* Some padding */
    cursor: pointer; /* Pointer/hand icon */
    width: 200%; /* Set a width if needed */
    display: block; /* Make the buttons appear below each other */
}

.btn-group button:not(:last-child) {
    border-bottom: none; /* Prevent double borders */
}

/* Add a background color on hover */
.btn-group button:hover {
    background-color: gray
}

 .panel-transparent {
    background: none;
}

.panel-transparent .panel-body{
    background: rgba(46, 51, 56, 0.2);
}

</style>
<div class=" col-sm-4">
    <div class="panel-body" >
      <a href="{% url 'SN:group_details' group.pk %}">
            {% if group.photo %}
                <img src="{{ group.photo.url }}" class="img-circle"
                     style="width:80px;height:80px;">
            {% else %}
                <h3>No image to display</h3>
            {% endif %}

            <a href="#" style="font-size:250%;color:#9d9d9d" >
                &nbsp; {{ group.name }}
            </a>
        </a>
    <br>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <div class="btn-group col-sm-offset-2">
        <a href="{% url 'SN:group_details' group.pk %}">
            <button>
                <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                 Group Home
            </button>
        </a>
        <a href="{% url 'SN:addpost_group' group.pk %}">
            <button>
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                Add post
            </button>
        </a>
        <a href="{% url 'SN:group_members' group.pk %}">
            <button>
                <i class="material-icons" style="font-size: large">group</i>
                Members
            </button>
        </a>
        {% if request.user != group.admin %}
        {% if is_member %}
            <a href="{% url 'SN:change_members' "leave" group.pk %}" >
            <button>
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                Leave Group
            </button>
            </a>
        {% else %}
            <a href="{% url 'SN:change_members' "join" group.pk %}" >
            <button>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Join Group
            </button>
            </a>
        {% endif %}
        {% else %}
             <a href="{% url 'SN:delete_group'  group.pk%}" >
             <button>
                <span class="glyphicon glyphicon-trash" aria-hidden="true">&nbsp;Delete </span>

            </button>
             </a>
        {% endif %}
    </div>
</div>
</div>
    <div ></div>





<br>
    <div class=" col-sm-4">
    <div class="panel-body" >
    <h1 style="color: black">Admin:</h1>
    <div class="row">&emsp;
            <a href="{% url 'SN:profile' admin.id%}" style="color: lightgray" >&emsp;
                    <div class="col-sm-3">
                    {% if admin.profile_pic %}
                        <img src="{{ admin.profile_pic.url }}" class="img-responsive" style="width:50px;height:50px;">
                    {% else %}
                        <h3>No image to display</h3>
                    {% endif %}
                    </div>
                    <div class="col-sm-6">

                        <h4>{{ admin.first_name }} {{ ' ' }} {{ admin.last_name }}</h4>
                    </div>
                    <div class="col-sm-1">

                    {% if admin != request.user %}
                        {% if admin in friends%}
                                <a href="{% url 'SN:change_friends' "Remove" admin.id %}" class="btn btn-info" role="button">

                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                    Unfollow
                                </a>
                        {% else %}
                            <a href="{% url 'SN:change_friends' "Add" admin.id %}" class="btn btn-info" role="button">
                             <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            Follow
                        </a>
                        {% endif %}
                    {% endif %}
                    </div>
            </a>

        </div>
        <br>
    <h1 style="color: black">Members <span style="font-size: large">({{ members.count }})</span>
            </h1>
        {% for member in members %}

        <div class="row">&emsp;
            <a href="{% url 'SN:profile' member.id%}" style="color: lightgray" >&emsp;
                    <div class="col-sm-3">
                    {% if member.profile_pic %}
                        <img src="{{ member.profile_pic.url }}" class="img-responsive" style="width:50px;height:50px;">
                    {% else %}
                        <h3>No image to display</h3>
                    {% endif %}
                    </div>
                    <div class="col-sm-6">

                        <h4>{{ member.first_name }} {{ ' ' }} {{ member.last_name }}</h4>
                    </div>
                    <div class="col-sm-1">

                    {% if request.user == group.admin %}
                        <a href="{% url 'SN:delete_member' group.pk member.id %}" class="btn btn-danger" role="button">

                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                        Remove
                        </a>
                    {% else%}
                        {% if member != request.user %}
                            {% if member in friends%}
                                    <a href="{% url 'SN:change_friends' "Remove" member.id %}" class="btn btn-info" role="button">

                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                        Unfollow
                                    </a>
                            {% else %}
                                <a href="{% url 'SN:change_friends' "Add" member.id %}" class="btn btn-info" role="button">
                                 <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                Follow
                            </a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                    </div>
            </a>

        </div>
        <br>
    {% endfor %}
    </div>
</div>
{% endblock %}